
# static is here: fistproject_static

# postgresql -- fistproject
# username -- kevintang
# password

"""
Django settings for trydjango18 project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
from django.conf import settings

if not settings.DEBUG:
	# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
	import os

	print ('Reading the Base.py')
	BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
	# root of project

	# Quick-start development settings - unsuitable for production
	# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

	# SECURITY WARNING: keep the secret key used in production secret!
	SECRET_KEY = 'kiur(*46sx__61htn)n^2hquf*55!83rc!bpm*ha_tgcmy3mrq'

	# SECURITY WARNING: don't run with debug turned on in production!
	DEBUG = False

	ADMINS = (
		("Kevin", "kevtang@gmail.com"),

		)

	ALLOWED_HOSTS = ['fistproject.org','www.fistproject.org']


	EMAIL_HOST = 'smtp.gmail.com'
	EMAIL_HOST_USER = 'ucl.fistproject@gmail.com'
	EMAIL_HOST_PASSWORD = '1Qe0S1B*ttS4D$4ZIW!0'
	EMAIL_PORT = 587
	EMAIL_USE_TLS = True

	# Application definition

	INSTALLED_APPS = (
	    # django app
	    'django.contrib.admin',
	    'django.contrib.auth',
	    'django.contrib.contenttypes',
	    'django.contrib.sessions',
	    'django.contrib.sites',
	    'django.contrib.messages',
	    'django.contrib.staticfiles',

	    # third party apps
	    'crispy_forms',
	    'registration',

	    # my apps
	    'newsletter',
	    'collector'
	)

	MIDDLEWARE_CLASSES = (
	    'whitenoise.middleware.WhiteNoiseMiddleware',
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	    'django.middleware.security.SecurityMiddleware',

	)

	ROOT_URLCONF = 'trydjango18.urls'

	TEMPLATES = [
	    {
	        'BACKEND': 'django.template.backends.django.DjangoTemplates',
	        'DIRS': [os.path.join(BASE_DIR, "templates")],
	        'APP_DIRS': True,
	        'OPTIONS': {
	            'context_processors': [
	                'django.template.context_processors.debug',
	                'django.template.context_processors.request',
	                'django.contrib.auth.context_processors.auth',
	                'django.contrib.messages.context_processors.messages',
	            ],
	        },
	    },
	]

	WSGI_APPLICATION = 'trydjango18.wsgi.application'

	DBPASS = '6cZKxywKv9qDHhQ'
	#from .db_password import DBPASS
	# Database
	# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
	# database_path = '/var/db/sear_project/'
	DATABASES = {
	    'default': {
	        'ENGINE': 'django.db.backends.postgresql_psycopg2',
	        'NAME': "fistproject",
	        'USER': "kevintang",
	        'PASSWORD': DBPASS,
	    }
	}


	# Internationalization
	# https://docs.djangoproject.com/en/1.8/topics/i18n/

	LANGUAGE_CODE = 'en-us'

	TIME_ZONE = 'UTC'

	USE_I18N = True

	USE_L10N = True

	USE_TZ = True


	# Static files (CSS, JavaScript, Images)
	# https://docs.djangoproject.com/en/1.8/howto/static-files/

	STATIC_URL = '/static/'

	STATIC_ROOT = '/home/kevintang/webapps/fistproject_static/'
	#os.path.join(os.path.dirname(BASE_DIR), "static_in_env","static_root")

	STATICFILES_DIRS = (
	    os.path.join(BASE_DIR, "static_in_pro","our_static"),
	    # os.path.join(BASE_DIR, "static_in_env"),
	    # '/var/www/static/',
	)

	MEDIA_URL = '/media/'
	MEDIA_ROOT = '/home/kevintang/webapps/fistproject_media/'
	#os.path.join(os.path.dirname(BASE_DIR), "static_in_env","media_root")


	# Crispy form tags settings
	CRISPY_TEMPLATE_PACK = 'bootstrap3'

	# Django Registration Redux settings
	ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window; you may, of course, use a different value.
	REGISTRATION_AUTO_LOGIN = True # Automatically log the user in.
	SITE_ID = 1
	LOGIN_REDIRECT_URL = '/'
